name: flutter_cli
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  interact: ^2.1.1
  dcli: any
  flutterfire_cli: ^0.1.1+2
  flutter_gen_runner: ^4.1.5
  flutter_flavorizr: ^2.1.2
  flutter_launcher_icons:
    git:
      url: https://github.com/RatakondalaArun/flutter_launcher_icons.git
      ref: fix/flutter-v2.8.0-support-321
  build_runner: ^2.1.7

dev_dependencies:
  lints: ^1.0.0
